version: "3.3"
services:
  metabase:
    volumes:
      - /metabase:/metabase
      - /metabase/data:/data
    environment:
      - MB_DB_FILE=/metabase/data/metabase.db
    ports:
      - 3000:3000
    image: metabase/metabase
    restart: always
